In [1]:
# import numpy module as np
import numpy as np

In [2]:
# asking for input
a = int(input("Enter the number of rows (a): "))

In [3]:
# asking for input
b = int(input("Enter the number of columns (b): "))

In [4]:
# generating random array
random_array = np.random.rand(a, b)

In [5]:
# calculating the mean for the given array
array_avg = np.mean(random_array)

In [6]:
# displaying the result
print("Generated Random Array:")
print(random_array)
print("Average of the array: {array_avg}")

Generated Random Array:
[[0.23097576 0.36986946 0.76247276]
 [0.72965475 0.6825661  0.93413225]
 [0.00313104 0.26544621 0.18951205]]
Average of the array: {array_avg}
