In [1]:
# import numpy module as np
import numpy as np

In [2]:
# creating a 3x4 matrix of all 0's
matrix = np.zeros((3, 4))

In [3]:
# loop for placing 1 in diagnol places
for i in range(min(matrix.shape)):
    matrix[i, i] = 1

In [4]:
# displaying the result
print("Matrix with 1's on the diagonal and 0's elsewhere (3x4):")
print(matrix)

Matrix with 1's on the diagonal and 0's elsewhere (3x4):
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
