In [1]:
# import numpy module as np
import numpy as np

In [2]:
# creating a 5x5 matrix where all row have values from 0-4
matrix = np.tile(np.arange(5), (5, 1))

In [3]:
# displaying the result
print("5x5 Matrix with row values ranging from 0 to 4:")
print(matrix)

5x5 Matrix with row values ranging from 0 to 4:
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
